baseurl = "/"
title = "My blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Justin's Rambings"
    description = "My description"
	linkedin = "https://www.linkedin.com/in/justin-mccannon-886537b6/"
    github = "https://github.com/justinbm26"
    email = "justinbm262@gmail.com"
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"


[[menu.main]]
name = "Blog"
url = "/"
weight = 1

#[[menu.main]]
#name = "Projects"
#url = "/project/"
#weight = 2

[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 4

[Permalinks]
    post = "/:filename/"
	
	

