baseurl = "/"
title = "My blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Justin's Rambings"
    description = "My description"
    github = "https://github.com/justinbm26"
    email = "justinbm262@gmail.com"
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"